#name = "homepage"
#
#containers:
web:
  ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "8600:8600/udp"
    - "8600:8600"
  image: docker.infoedge.com:5000/naukri/consul
  volumes:
    - ./config/:/etc/supervisor/conf.d/
    - ../consul:/consul
    - ./discovery/current:/apps/service/current
